import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Button, C, Field, Header } from "../../components/UI";
import { Priority, useApp } from "../../context/AppContext";

export default function ActivityForm(){
 const {mode,id}=useLocalSearchParams<{mode?:string;id?:string}>();const router=useRouter();const {activities,subjects,updateActivity}=useApp();const old=activities.find(a=>a.id===id);
 const [title,setTitle]=useState(old?.title||"");const [description,setDescription]=useState(old?.description||"");const [subject,setSubject]=useState(old?.subject||"");const [dueDate,setDueDate]=useState(old?.dueDate||"");const [priority,setPriority]=useState<Priority>(old?.priority||"Medium");const [attachment,setAttachment]=useState(old?.attachment||"");
 const [subjectPickerVisible,setSubjectPickerVisible]=useState(false);
 const subjectOptions=Array.from(new Set([subject,...subjects.map(item=>item.name)].filter(Boolean)));
 const save=()=>{if(!id||!title.trim())return Alert.alert("Missing title","Title is required.");if(!subject.trim())return Alert.alert("Missing subject","Please select a subject.");updateActivity(id,{title,description,subject,dueDate,priority,attachment});Alert.alert("Updated","Activity updated successfully.",[{text:"OK",onPress:()=>router.back()}]);};
 return <><ScrollView style={s.screen} contentContainerStyle={s.content}><Header title="Edit Activity" onBack={()=>router.back()}/><Field label="Activity Title" value={title} onChangeText={setTitle}/><Text style={s.label}>Subject</Text><TouchableOpacity onPress={()=>setSubjectPickerVisible(true)} style={s.subjectPicker} accessibilityRole="button"><Text style={s.subjectValue}>{subject||"Select a subject"}</Text><Ionicons name="chevron-down" size={16} color={C.muted}/></TouchableOpacity><Field label="Description" value={description} onChangeText={setDescription} multiline/><Field label="Due Date" value={dueDate} onChangeText={setDueDate}/><Field label="Attachment" value={attachment} onChangeText={setAttachment}/><Text style={s.label}>Priority</Text><View style={s.prios}>{(["High","Medium","Low"] as Priority[]).map(p=><TouchableOpacity key={p} onPress={()=>setPriority(p)} style={[s.prio,priority===p&&s.selected]}><Text style={s.text}>{p}</Text></TouchableOpacity>)}</View><Button title="SAVE CHANGES" onPress={save}/></ScrollView><Modal visible={subjectPickerVisible} transparent animationType="fade" onRequestClose={()=>setSubjectPickerVisible(false)}><View style={s.backdrop}><View style={s.subjectModal}><Text style={s.modalTitle}>Select Subject</Text><ScrollView style={s.options}>{subjectOptions.map(option=><TouchableOpacity key={option} onPress={()=>{setSubject(option);setSubjectPickerVisible(false);}} style={s.option}><Text style={s.optionText}>{option}</Text></TouchableOpacity>)}</ScrollView><TouchableOpacity onPress={()=>setSubjectPickerVisible(false)} style={s.cancel}><Text style={s.cancelText}>Cancel</Text></TouchableOpacity></View></View></Modal></>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:35},label:{color:C.muted,fontWeight:"700",fontSize:12,marginBottom:7},subjectPicker:{height:50,borderRadius:13,backgroundColor:C.card,borderWidth:1,borderColor:C.border,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14,marginBottom:14},subjectValue:{color:C.text},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,0.65)",justifyContent:"center",padding:22},subjectModal:{maxHeight:"80%",backgroundColor:C.card,borderRadius:16,borderWidth:1,borderColor:C.border,padding:16},modalTitle:{color:C.text,fontSize:18,fontWeight:"800",marginBottom:12},options:{flexGrow:0},option:{minHeight:46,justifyContent:"center",borderBottomWidth:1,borderBottomColor:C.border},optionText:{color:C.text,fontSize:14},cancel:{alignItems:"center",paddingTop:14},cancelText:{color:C.blue,fontWeight:"800"},prios:{flexDirection:"row",gap:8,marginBottom:20},prio:{flex:1,paddingVertical:11,borderRadius:10,borderWidth:1,borderColor:C.border,backgroundColor:C.card,alignItems:"center"},selected:{backgroundColor:C.blue,borderColor:C.blue},text:{color:"#fff",fontWeight:"800",fontSize:11}});
