import { useLocalSearchParams, useRouter } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { C, Card, Header } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function StudentDetails(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const {users,tasks}=useApp();const st=users.find(u=>u.id===id);if(!st)return <View style={s.screen}><Header title="Student" onBack={()=>router.back()}/><Text style={s.none}>Student not found.</Text></View>;
 const studentTasks=tasks.filter(task=>task.userId===st.id);const completed=studentTasks.filter(task=>task.completed).length;return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header title="Student Details" onBack={()=>router.back()}/><View style={s.avatar}><Text style={s.initial}>{st.name.slice(0,1)}</Text></View><Text style={s.name}>{st.name}</Text><Text style={s.mutedCenter}>{st.email}</Text><Card style={s.info}><Text style={s.label}>Student ID</Text><Text style={s.value}>{st.studentId||"—"}</Text><Text style={s.label}>Course</Text><Text style={s.value}>{st.course||"—"}</Text><Text style={s.label}>Year Level</Text><Text style={s.value}>{st.year||"—"}</Text></Card><View style={s.stats}><Card style={s.stat}><Text style={s.num}>{studentTasks.length}</Text><Text style={s.muted}>Tasks</Text></Card><Card style={s.stat}><Text style={s.num}>{completed}</Text><Text style={s.muted}>Completed</Text></Card></View><Text style={s.section}>Assignments</Text>{studentTasks.length===0?<Text style={s.empty}>No assignments recorded for this student.</Text>:studentTasks.map(task=><Card key={task.id} style={s.task}><View style={{flex:1}}><Text style={s.taskTitle}>{task.title}</Text><Text style={s.taskSubject}>{task.subject} • Due {task.dueDate}</Text>{task.completed&&<Text style={s.completedAt}>{task.completedAt?`Completed ${new Date(task.completedAt).toLocaleString()}`:"Completed"}</Text>}</View><View style={[s.status,task.completed?s.done:s.pending]}><Text style={s.statusText}>{task.completed?"Done":"Pending"}</Text></View></Card>)}</ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:35},avatar:{alignSelf:"center",width:90,height:90,borderRadius:45,backgroundColor:C.purple,alignItems:"center",justifyContent:"center",marginTop:16},initial:{color:"#fff",fontWeight:"800",fontSize:38},name:{color:"#fff",fontSize:22,fontWeight:"800",textAlign:"center",marginTop:14},mutedCenter:{color:C.muted,textAlign:"center",fontSize:11,marginTop:4},info:{marginTop:20},label:{color:C.muted2,fontSize:10,marginTop:5},value:{color:"#fff",fontWeight:"700",marginTop:4,marginBottom:10},stats:{flexDirection:"row",gap:9,marginTop:12},stat:{flex:1},num:{color:"#fff",fontSize:24,fontWeight:"800"},muted:{color:C.muted,fontSize:10,marginTop:4},section:{color:C.text,fontSize:17,fontWeight:"800",marginTop:22,marginBottom:10},empty:{color:C.muted,textAlign:"center",paddingVertical:18},task:{flexDirection:"row",alignItems:"center",marginBottom:9,gap:10},taskTitle:{color:C.text,fontSize:13,fontWeight:"800"},taskSubject:{color:C.muted,fontSize:10,marginTop:4},completedAt:{color:C.green,fontSize:10,marginTop:4},status:{paddingHorizontal:9,paddingVertical:6,borderRadius:8},done:{backgroundColor:"#16764E"},pending:{backgroundColor:C.card2},statusText:{color:C.text,fontSize:10,fontWeight:"800"},none:{color:C.muted,textAlign:"center"}});
