import { Ionicons } from "@expo/vector-icons";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { Card, C, PriorityBadge } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function StudentHome() {
 const router=useRouter(); const {currentUser,tasks,activities,notifications}=useApp();
 const done=tasks.filter(t=>t.completed).length; const pct=tasks.length?Math.round(done/tasks.length*100):0;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}>
  <View style={s.header}><View><Text style={s.small}>Good Morning!</Text><Text style={s.name}>{currentUser?.name?.split(" ")[0] || "Student"}</Text></View><TouchableOpacity style={s.notif} onPress={()=>router.push("/(student)/notifications")}><Ionicons name="notifications-outline" size={22} color="#fff"/>{notifications.some(n=>!n.read)&&<View style={s.dot}/>}</TouchableOpacity></View>
  <Card><View style={s.row}><View><Text style={s.muted}>Today's Progress</Text><Text style={s.percent}>{pct}%</Text></View><View style={s.circle}><Text style={s.circleText}>{done}/{tasks.length}</Text></View></View><View style={s.progress}><View style={[s.fill,{width:`${pct}%`}]}/></View><Text style={s.muted}>{done} of {tasks.length} tasks completed</Text></Card>
  <View style={s.sectionRow}><Text style={s.section}>Today's Tasks</Text><TouchableOpacity onPress={()=>router.push("/(student)/tasks")}><Text style={s.link}>See all</Text></TouchableOpacity></View>
  {tasks.filter(t=>!t.completed).slice(0,3).map(t=><TouchableOpacity key={t.id} onPress={()=>router.push("/(student)/tasks")}><Card style={s.task}><View style={s.box}/><View style={{flex:1}}><Text style={s.title}>{t.title}</Text><Text style={s.muted}>{t.subject} • Due {t.dueDate}</Text></View><PriorityBadge priority={t.priority}/></Card></TouchableOpacity>)}
  <View style={s.sectionRow}><Text style={s.section}>Latest Activities</Text><TouchableOpacity onPress={()=>router.push("/(student)/notifications")}><Text style={s.link}>Notifications</Text></TouchableOpacity></View>
  {activities.slice(0,3).map(a=><TouchableOpacity key={a.id} onPress={()=>router.push({pathname:"/(student)/activity-details",params:{id:a.id}})}><Card style={s.task}><Ionicons name="document-text-outline" size={25} color={C.blue}/><View style={{flex:1,marginLeft:12}}><Text style={s.title}>{a.title}</Text><Text style={s.muted}>{a.subject} • Due {a.dueDate}</Text></View></Card></TouchableOpacity>)}
 </ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:35},header:{paddingTop:55,paddingBottom:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},small:{color:C.muted,fontSize:13},name:{color:"#fff",fontSize:27,fontWeight:"800",marginTop:3},notif:{width:44,height:44,borderRadius:14,backgroundColor:C.card,alignItems:"center",justifyContent:"center"},dot:{width:8,height:8,borderRadius:4,backgroundColor:C.red,position:"absolute",right:10,top:9},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},muted:{color:C.muted,fontSize:11,marginTop:3},percent:{color:"#fff",fontSize:31,fontWeight:"800",marginTop:4},circle:{width:62,height:62,borderRadius:31,borderWidth:7,borderColor:C.blue,alignItems:"center",justifyContent:"center"},circleText:{color:"#fff",fontWeight:"800",fontSize:11},progress:{height:8,backgroundColor:"#1B2C43",borderRadius:5,marginTop:16,overflow:"hidden"},fill:{height:"100%",backgroundColor:C.blue},sectionRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:22,marginBottom:9},section:{color:"#fff",fontSize:18,fontWeight:"800"},link:{color:"#6E91FF",fontWeight:"700",fontSize:11},task:{flexDirection:"row",alignItems:"center",marginBottom:9},box:{width:20,height:20,borderWidth:1.5,borderColor:C.muted2,borderRadius:6,marginRight:12},title:{color:"#fff",fontWeight:"800",fontSize:13}});
