import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { C, Card, Header } from "../../components/UI";
import { useApp } from "../../context/AppContext";

export default function StudentDetails(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const {users,tasks}=useApp();const st=users.find(u=>u.id===id);if(!st)return <View style={s.screen}><Header title="Student" onBack={()=>router.back()}/><Text style={s.none}>Student not found.</Text></View>;
 const completed=tasks.filter(t=>t.completed).length;return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header title="Student Details" onBack={()=>router.back()}/><View style={s.avatar}><Text style={s.initial}>{st.name.slice(0,1)}</Text></View><Text style={s.name}>{st.name}</Text><Text style={s.mutedCenter}>{st.email}</Text><Card style={s.info}><Text style={s.label}>Student ID</Text><Text style={s.value}>{st.studentId||"—"}</Text><Text style={s.label}>Course</Text><Text style={s.value}>{st.course||"—"}</Text><Text style={s.label}>Year Level</Text><Text style={s.value}>{st.year||"—"}</Text></Card><View style={s.stats}><Card style={s.stat}><Text style={s.num}>{tasks.length}</Text><Text style={s.muted}>Tasks</Text></Card><Card style={s.stat}><Text style={s.num}>{completed}</Text><Text style={s.muted}>Completed</Text></Card></View></ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:35},avatar:{alignSelf:"center",width:90,height:90,borderRadius:45,backgroundColor:C.purple,alignItems:"center",justifyContent:"center",marginTop:16},initial:{color:"#fff",fontWeight:"800",fontSize:38},name:{color:"#fff",fontSize:22,fontWeight:"800",textAlign:"center",marginTop:14},mutedCenter:{color:C.muted,textAlign:"center",fontSize:11,marginTop:4},info:{marginTop:20},label:{color:C.muted2,fontSize:10,marginTop:5},value:{color:"#fff",fontWeight:"700",marginTop:4,marginBottom:10},stats:{flexDirection:"row",gap:9,marginTop:12},stat:{flex:1},num:{color:"#fff",fontSize:24,fontWeight:"800"},muted:{color:C.muted,fontSize:10,marginTop:4},none:{color:C.muted,textAlign:"center"}});
